-- Création de la base de données
CREATE DATABASE IF NOT EXISTS monbaseDeDonneVenteFilm;
USE monbaseDeDonneVenteFilm;

-- Supprimer les tables si elles existent (ordre inverse des dépendances)
DROP TABLE IF EXISTS VENTE_PRODUIT;
DROP TABLE IF EXISTS ACHETER;
DROP TABLE IF EXISTS VENDEUR;
DROP TABLE IF EXISTS PRODUIT;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS UTILISATEURS;

-- Table CLIENT
CREATE TABLE CLIENT (
    ID_CLIENT INT AUTO_INCREMENT PRIMARY KEY,
    NomCli VARCHAR(50) NOT NULL,
    PrenomCli VARCHAR(50) NOT NULL,
    EmailCli VARCHAR(100) NOT NULL UNIQUE,
    AdresseCli VARCHAR(255),
    Ville VARCHAR(50),
    Pays VARCHAR(50),
    Preferences TEXT,
    TelephoneCli VARCHAR(20),
    PhotoCli VARCHAR(255)
);

-- Table PRODUIT (Film)
CREATE TABLE PRODUIT (
    ID_PROD INT AUTO_INCREMENT PRIMARY KEY,
    Titre VARCHAR(100) NOT NULL,
    Realisateur VARCHAR(100),
    DateSortie DATE,
    Photo VARCHAR(255),
    Duree INT,
    PaysOrigine VARCHAR(50),
    ActeursPrincipaux TEXT,
    Prix_unitaire DECIMAL(10,2) NOT NULL,
    Langue VARCHAR(50),
    Genre VARCHAR(50)
);

-- Table VENDEUR
CREATE TABLE VENDEUR (
    ID_VENDEUR INT AUTO_INCREMENT PRIMARY KEY,
    NomVendeur VARCHAR(50) NOT NULL,
    PrenomVendeur VARCHAR(50) NOT NULL,
    CIN VARCHAR(20) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Telephone VARCHAR(20),
    Adresse VARCHAR(255),
    PhotoVendeur VARCHAR(255)
);

-- Table ACHETER (relation client-produit)
CREATE TABLE ACHETER (
    ID_ACHAT INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENT INT,
    ID_PROD INT,
    DateAchat DATETIME NOT NULL,
    Prix_unitaire DECIMAL(10,2) NOT NULL,
    Quantite INT NOT NULL,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT) ON DELETE CASCADE,
    FOREIGN KEY (ID_PROD) REFERENCES PRODUIT(ID_PROD) ON DELETE CASCADE
);

-- Table VENTE_PRODUIT (relation produit-vendeur)
CREATE TABLE VENTE_PRODUIT (
    ID_VENTE INT AUTO_INCREMENT PRIMARY KEY,
    ID_PROD INT,
    ID_VENDEUR INT,
    DateVente DATETIME NOT NULL,
    FOREIGN KEY (ID_PROD) REFERENCES PRODUIT(ID_PROD) ON DELETE CASCADE,
    FOREIGN KEY (ID_VENDEUR) REFERENCES VENDEUR(ID_VENDEUR) ON DELETE CASCADE
);

-- Table UTILISATEURS (pour l'authentification)
CREATE TABLE UTILISATEURS (
    ID_USER INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Role ENUM('admin', 'user') DEFAULT 'admin',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
